### ISSUE TITLE
Error in BVAR with exogenous variables

### ISSUE THREAD

**Issue by joaoleal1990** [european-central-bank/BEAR-toolbox#10]
Dear all,

When running a BVAR with an exogenous variable I get the following error message I am unable to sort. All info is in the excel tab so I am really lost... Would you be able to help? :)
Many thanks
![Capture](https://user-images.githubusercontent.com/94900595/143007690-89166cff-1bf7-4abd-8aa2-0dca3148d853.PNG)
!

**Comment by ebenetce** [comment]
Hello @joaoleal1990 , the latest release should fix this bug. If you would try re-installing BEAR.mltbx, and check that would be great.

**Comment by joaoleal1990** [comment]
> Hello @joaoleal1990 , the latest release should fix this bug. If you would try re-installing BEAR.mltbx, and check that would be great.

Indeed, all sorted :) There is just one additional issue, regarding the Grid-search functionality. I keep getting the following error message. Is it something that can be deal with? Thanks a million
![Capture](https://user-images.githubusercontent.com/94900595/143460599-9ef8d6c0-a1a4-45ee-9192-d9d18970dba6.PNG)
n!

**Comment by ebenetce** [comment]
I will open a separate issue for it thanks!
