### ISSUE TITLE
Problem in MF-VAR with s.IRF=0

### ISSUE THREAD

**Issue by ckarag** [european-central-bank/BEAR-toolbox#29]
Hi. I am estimating an MF-VAR using the German data and the settings provided by the toolbox (-the settings I am using are those found in the path: C:\Users\... \MathWorks\MATLAB Add-Ons\Toolboxes\BEAR toolbox\examples\bear_settings_MF.m). Everything is as expected. The model is estimated without any problems, and the results are saved in the Excel file. 
However, when I change setting s.IRF=0 I get the following error (-also attached as a screenshot):

```
Unrecognized function or variable 'IRF'.
Error in bear.data.excelrecord1fcn (line 442)
elseif IRF==0
Error in BEARmain (line 468)
[estimationinfo] = bear.data.excelrecord1fcn(endo, exo, Units, opts);   
```  

![IRF=0](https://user-images.githubusercontent.com/60855543/182458438-91a2669c-e8d7-4435-9f24-ef0f792f295a.png)

**Comment by ebenetce** [comment]
the issue is in line 442 of excelrecord1fcn.m instead of IRF==0 it should be
opts.IRF == 0

I will try to push the changes, but for now, if you type:
edit bear.data.excelrecord1fcn

and make the edit manually, it should work

**Comment by ckarag** [comment]
> the issue is in line 442 of excelrecord1fcn.m instead of IRF==0 it should be opts.IRF == 0
> 
> I will try to push the changes, but for now, if you type: edit bear.data.excelrecord1fcn
> 
> and make the edit manually, it should work

Thank you Eduard!
