### ISSUE TITLE
The data.xlsx template does not have 2 sheets!

### ISSUE THREAD

**Issue by binhpham79** [european-central-bank/BEAR-toolbox#3]
Hi,

When running the time-varying model, the BEAR 5.0 threw an error as below: 

Maybe, the data.xlsx does not have 2 sheets: "exo mean priors" and "exo tight priors". Please provide the correct excel template.

-------------------------------------------------------------------------
Error using xlsread (line 257)
Worksheet 'exo mean priors' not found.

Error in gensample (line 255)
    [priorexo]=xlsread('data.xlsx','exo mean priors');

Error in bear_toolbox_main_code (line 93)
        =gensample(startdate,enddate,VARtype,Fstartdate,Fenddate,Fendsmpl,endo,exo,frequency,lags,F,CF,ar,lambda4,PriorExcel,priorsexogenous,pref,favar,IRFt);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

**Comment by ebenetce** [comment]
The default file in tbx/default_bear_data.xlsx has these two files
