### ISSUE TITLE
Does not work in Matlab R2019a

### ISSUE THREAD

**Issue by MacroPY** [european-central-bank/BEAR-toolbox#32]
Dear, I have problems, the new app does not work with Matlab R2019a, I get an error every time I try to run a model or an example.

I don't know if you can see the image, but it tells me that something is wrong, it asks me to check an error in a multiplication operator or something like that.

Can anyone help me?

![image](https://user-images.githubusercontent.com/46204183/200138899-72d5b5d5-d3cf-4396-851e-5bca62368fbb.png)

**Comment by ebenetce** [comment]
The code won't work in this version of MATLAB. You have the following options:

- Try using 20a or newer
- Use MATLAB Online
- Some of the [releases](https://github.com/european-central-bank/BEAR-toolbox/releases) have a .exe which install BEAR as a standalone tool that does not require MATLAB.
