### ISSUE TITLE
Favar default

### ISSUE THREAD

**Issue by Thidmg** [european-central-bank/BEAR-toolbox#5]
Hi, i would like to run a favar model but i didn't see how to run it in the user guide.

So i tried to run the dafault program with the default data excel of favar. I only change the dates in the bear to monthly like this image and put the data on excel of the FYFF of the funds rate(like theses images bellow).

 I could run only the ols favar but not the bayesian favar.

 With the bayesian favar these erros bellow occurs

![favarbearexcel](https://user-images.githubusercontent.com/74992941/122682394-7cf81280-d1cf-11eb-8d31-d72bb26a2b12.png)

![favarbear](https://user-images.githubusercontent.com/74992941/122682395-81243000-d1cf-11eb-9955-4658262260a9.png)

![favarbear2](https://user-images.githubusercontent.com/74992941/122682396-81bcc680-d1cf-11eb-9026-f8e7ea4e622d.png)

The error is:

Index in position 2 exceeds array bounds (must not exceed 1).

Error in favar_gensample3 (line 15)
    Lf=[Lf(1:numpc,:);Lfy(:,1:numpc)];

Error in gensample (line 165)
    [data_endo,favar]=favar_gensample3(data_endo,favar);

Error in bear_toolbox_main_code (line 93)
        =gensample(startdate,enddate,VARtype,Fstartdate,Fenddate,Fendsmpl,endo,exo,frequency,lags,F,CF,ar,lambda4,PriorExcel,priorsexogenous,pref,favar,IRFt);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in bear5 (line 53)
    run(fullfile('files','bear_toolbox_main_code.m'));

**Comment by ebenetce** [comment]
Hello @Thidmg , we just pushed an updated version of the toolbox to the repository. In that new version if you open the BEARapp and select "Import>replications>Amir ..", you will get an example on how to run BVAR with FAVAR. Could you give it a try and see if that solves the issues?

**Comment by Thidmg** [comment]
Hi, thanks! That toolbox don't run in matlab2019a?  
I could run the favar after i see the replication settings in the last version of bear. You changed the codes from the last version?

If yes i will update my matlab to 2021a, because my results from gibbs sample using favar are not converging, even if i put more then 100000 iterations.  

Thanks!
